apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-volume
  name: nginx-volume
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-volume
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-volume
        version: v1
    spec:
      volumes:
      - name: nginx-pvc
        persistentVolumeClaim:
          claimName: nginx-pvc
      containers:
      - image: nginx:1.7.9
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
          - mountPath: "/www"
            name: nginx-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
